## NumPy Arrays

In [2]:
import numpy as np

In [3]:
list = [1,2,3]

In [5]:
arr = np.array(list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [ ]:
np.eye(4) #For identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5) #Random number between 0 and 1

array([0.68525297, 0.09455068, 0.87333344, 0.8204706 , 0.26545748])

In [22]:
np.random.rand(5,5)

array([[0.64186958, 0.04095064, 0.1347858 , 0.8691211 , 0.82718587],
       [0.15609685, 0.32817206, 0.49161959, 0.19252247, 0.83066691],
       [0.37946553, 0.95112828, 0.20294034, 0.33874552, 0.28296033],
       [0.93202594, 0.54245518, 0.36979881, 0.73752357, 0.32227526],
       [0.69520835, 0.91033204, 0.106626  , 0.36560224, 0.78125836]])

In [24]:
np.random.randn(2,4) #Random number from standard normal distribution

array([[-0.90458023, -2.73068759, -0.20672744, -0.31013856],
       [ 0.08959061, -0.14621233, -0.10462592,  0.01332893]])

In [26]:
np.random.randint(1,100,10)#Random integers between 1 and 100

array([34, 27, 80, 19, 41, 55, 23, 10, 53, 88], dtype=int32)

In [40]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
ranarr

array([ 3, 15, 32,  9, 38,  0, 40, 24, 12,  4], dtype=int32)

In [ ]:
arr.reshape(5,5)#Needs to have the same number of elements, so 25 elements can be reshaped to 5x5, but not to 4x4.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
print(ranarr.max())
print(ranarr.argmax()) #Returns the index of the maximum value
print(ranarr.min())
print(ranarr.argmin()) #Returns the index of the minimum value

40
6
0
5


In [41]:
print(arr.shape) #Returns the shape of the array
arr = arr.reshape(5,5)
print(arr.shape)

(25,)
(5, 5)


In [43]:
arr.dtype

dtype('int64')

In [44]:
from numpy.random import randint

In [45]:
randint(0,100)

3

## NumPy Array Indexing and Selection

In [1]:
import numpy as np

In [12]:
arrI = np.arange(0,11)

In [13]:
arrI

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arrI[8]

np.int64(8)

In [7]:
print(arrI[1:5]) #Slicing, returns elements from index 1 to 4
print(arrI[0:5]) #Slicing, returns elements from index 0 to 4
print(arrI[:6]) #Slicing, returns elements from index 0 to 5
print(arrI[5:]) #Slicing, returns elements from index 5 to the end

[1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4 5]
[ 5  6  7  8  9 10]


In [14]:
print(arrI)

slice_of_arrI = arrI[0:5]
slice_of_arrI[:] = 100

print(slice_of_arrI)
print(arrI)#O slice_of_arrI é uma view do arrI, então quando alteramos o slice_of_arrI, o arrI também é alterado

[ 0  1  2  3  4  5  6  7  8  9 10]
[100 100 100 100 100]
[100 100 100 100 100   5   6   7   8   9  10]


In [15]:
arrI_copy = arrI.copy() #Diferente do slice, o copy cria uma cópia do array, então quando alteramos o copy, o arrI não é alterado

In [16]:
arrI_copy[:] = 200

In [17]:
print(arrI)
print(arrI_copy)

[100 100 100 100 100   5   6   7   8   9  10]
[200 200 200 200 200 200 200 200 200 200 200]


In [18]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [19]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
print(arr_2d[1][1]) #Retorna o elemento da segunda linha e segunda coluna, que é 25
print(arr_2d[0]) #Retorna a primeira linha do array, que é [5,10,15]
print(arr_2d[0:2]) #Retorna as duas primeiras linhas do array, que são [[5,10,15],[20,25,30]]
print(arr_2d[2][1]) #Retorna o elemento da terceira linha e segunda coluna, que é 40

# Outra notação para acessar elementos de arrays 2D é usando vírgula para separar os índices de linha e coluna:

print(arr_2d[1,1]) #Retorna o elemento da segunda linha e segunda coluna, que é 25
print(arr_2d[:2,1:]) #Retorna as duas primeiras linhas e todas as colunas a partir da segunda coluna, que são [[10,15],[25,30]]
print(arr_2d[1:,:2]) #Retorna todas as linhas a partir da segunda linha e as duas primeiras colunas, que são [[20,25],[35,40]]

25
[ 5 10 15]
[[ 5 10 15]
 [20 25 30]]
40
25
[[10 15]
 [25 30]]
[[20 25]
 [35 40]]


In [26]:
arr_1d = np.arange(1,11)

In [27]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
bool_arr_1d =  arr_1d > 5

In [31]:
bool_arr_1d

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [33]:
arr_1d[bool_arr_1d] #Retorna os elementos do arr_1d que são maiores que 5

array([ 6,  7,  8,  9, 10])

In [34]:
arr_1d[arr_1d > 3] #Retorna os elementos do arr_1d que são maiores que 3

array([ 4,  5,  6,  7,  8,  9, 10])

#### Exercise:

Create a new 2d array with np.arange(50) and reshape it to be 5,10.

Than grab chunks of it.

In [36]:
arr_2D = np.arange(50).reshape(5,10)

In [37]:
arr_2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [38]:
print(arr_2D[1:3, 2:5]) #Retorna as linhas 1 e 2 e as colunas 2, 3 e 4 do array arr_2D
print(arr_2D[:2, 5:]) #Retorna as duas primeiras linhas e as colunas a partir da quinta coluna do array arr_2D

[[12 13 14]
 [22 23 24]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]


## NumPy Operations

    - Array with Array
    - Array with Scalars
    - Universal Array Functions

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
print(arr + 100)
print(arr * 2)
print(arr ** 2) #Eleva cada elemento do array ao quadrado

[100 101 102 103 104 105 106 107 108 109 110]
[ 0  2  4  6  8 10 12 14 16 18 20]
[  0   1   4   9  16  25  36  49  64  81 100]


In [10]:
arr / arr #retorna nan para o elemento 0, pois não é possível dividir por 0

C:\Users\gabri\AppData\Local\Temp\ipykernel_24484\55995797.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr #retorna nan para o elemento 0, pois não é possível dividir por 0


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
np.sqrt(arr) #Retorna a raiz quadrada de cada elemento do array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [12]:
np.exp(arr) #Retorna o exponencial de cada elemento do array

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [13]:
np.log(arr) #Retorna o logaritmo natural de cada elemento do array

C:\Users\gabri\AppData\Local\Temp\ipykernel_24484\2859866470.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) #Retorna o logaritmo natural de cada elemento do array


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [14]:
np.sin(arr) #Retorna o seno de cada elemento do array

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])