# NumPy para Análise de Malware

Essas anotações foram reorganizadas a partir do notebook original de NumPy.

Eu mantive o conteúdo base, traduzi as partes que estavam em inglês, deixei os comentários mais claros e adicionei explicações voltadas para o meu projeto de pesquisa.

O foco aqui não é virar “mago do NumPy” do nada. O foco é entender o suficiente para usar NumPy como ferramenta de preparação de dados, representação de binários, manipulação de matrizes e suporte para machine learning/deep learning.

## Por que NumPy importa nesse projeto?

No meu TCC, eu provavelmente vou lidar com coisas como:

- bytes extraídos de arquivos;
- matrizes que representam imagens de binários;
- features numéricas;
- labels de famílias de malware;
- scores de modelos;
- filtros e máscaras;
- normalização de dados.

NumPy ajuda justamente nisso: trabalhar com muitos números de forma eficiente e organizada.

Sem NumPy, eu fico preso em lista comum e loop manual. Com NumPy, eu consigo pensar em vetor, matriz, imagem e processamento em lote.

## NumPy Arrays

NumPy é uma das bibliotecas mais importantes para trabalhar com dados numéricos em Python.

A ideia central aqui é simples: em vez de trabalhar com listas comuns do Python, eu passo a trabalhar com **arrays**, que são estruturas mais eficientes para cálculo, matriz, imagem, vetor de features e qualquer coisa que precise ser processada em lote.

No meu projeto de análise de malware, isso importa bastante porque binários podem virar sequências de bytes, sequências de bytes podem virar arrays, arrays podem virar matrizes, e matrizes podem virar imagens para treinar modelos depois.

Ou seja: NumPy é meio que a ponte entre “tenho dados crus” e “tenho algo que um modelo consegue consumir”.

**Importando o NumPy**

Normalmente a biblioteca é importada como `np`. Isso é uma convenção muito comum, então vale seguir esse padrão desde o começo.

In [2]:
import numpy as np

**Lista comum vs array NumPy**

Aqui começa com uma lista normal do Python. Eu deixei o conteúdo como estava no notebook original, mas um detalhe importante: em projeto real eu evitaria usar o nome `list` como variável, porque `list` também é o nome de uma função interna do Python.

Não quebra esse exemplo, mas pode virar dor de cabeça depois.

In [3]:
list = [1,2,3]

In [5]:
arr = np.array(list)

In [6]:
arr

array([1, 2, 3])

**Matriz**

Uma matriz nada mais é do que uma lista de listas. Para o meu projeto, essa ideia é importante porque uma imagem é basicamente uma matriz de valores.

Quando eu transformar bytes de um binário em imagem, cada número pode representar a intensidade de um pixel.

In [7]:
my_matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Ideia para a pesquisa**

Se um binário for lido como bytes, eu posso transformar essa sequência em um array NumPy. Depois, se eu reorganizar esse array em uma matriz, começo a chegar na ideia de representação visual de malware.

Exemplo conceitual:

`arquivo.exe -> bytes -> array NumPy -> matriz -> imagem -> CNN`

Essa é uma das pontes mais importantes entre baixo nível e deep learning.

**Criando arrays automaticamente**

`np.arange()` cria uma sequência de números. Ele parece com o `range()` do Python, só que já devolve um array NumPy.

Isso é útil para simular dados, criar índices e montar exemplos rápidos sem precisar digitar tudo manualmente.

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

**Arrays de zeros**

`np.zeros()` cria uma matriz preenchida com zero.

Na pesquisa, isso pode servir para inicializar uma imagem vazia, criar um placeholder para features, ou completar dados quando alguma amostra não tiver determinado valor.

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Arrays de uns**

`np.ones()` cria uma matriz preenchida com 1.

Pode parecer besta, mas é útil quando eu preciso criar máscaras, pesos iniciais simples, ou matrizes auxiliares.

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**`linspace`**

`np.linspace()` cria vários valores igualmente espaçados entre um início e um fim.

Em pesquisa, isso pode ser útil para testar limiares. Por exemplo: testar thresholds entre 0 e 1 para decidir quando um score vira `malware` ou `benigno`.

In [18]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

**Matriz identidade**

`np.eye()` cria uma matriz identidade.

Ela aparece bastante em matemática, álgebra linear e machine learning. Talvez eu não use diretamente todo dia na análise de malware, mas entender isso ajuda quando o assunto começa a envolver vetores, matrizes, projeções e modelos.

In [ ]:
np.eye(4) # matriz identidade

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Números aleatórios**

Essas funções geram dados aleatórios. Isso é útil para testar código antes de ter o dataset real.

No meu caso, posso usar dados aleatórios para testar se o pipeline está funcionando antes de colocar amostras reais ou features reais.

In [21]:
np.random.rand(5) # números aleatórios entre 0 e 1

array([0.68525297, 0.09455068, 0.87333344, 0.8204706 , 0.26545748])

In [22]:
np.random.rand(5,5)

array([[0.64186958, 0.04095064, 0.1347858 , 0.8691211 , 0.82718587],
       [0.15609685, 0.32817206, 0.49161959, 0.19252247, 0.83066691],
       [0.37946553, 0.95112828, 0.20294034, 0.33874552, 0.28296033],
       [0.93202594, 0.54245518, 0.36979881, 0.73752357, 0.32227526],
       [0.69520835, 0.91033204, 0.106626  , 0.36560224, 0.78125836]])

In [24]:
np.random.randn(2,4) # números aleatórios de uma distribuição normal padrão

array([[-0.90458023, -2.73068759, -0.20672744, -0.31013856],
       [ 0.08959061, -0.14621233, -0.10462592,  0.01332893]])

In [26]:
np.random.randint(1,100,10)# números inteiros aleatórios entre 1 e 100

array([34, 27, 80, 19, 41, 55, 23, 10, 53, 88], dtype=int32)

**Nota importante sobre aleatoriedade**

Resultados aleatórios mudam a cada execução. Se eu quiser reprodutibilidade no TCC, preciso usar seed, tipo:

`np.random.seed(42)`

Isso faz diferença porque um TCC precisa conseguir explicar e repetir resultados, não só “rodou uma vez e deu bom”.

**Reshape e formato dos dados**

Aqui o array tem 25 elementos. Depois ele vai ser reorganizado como uma matriz 5x5.

Essa é uma das ideias mais importantes para o meu TCC: pegar uma sequência linear de dados e transformar em matriz/imagem.

In [40]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
ranarr

array([ 3, 15, 32,  9, 38,  0, 40, 24, 12,  4], dtype=int32)

In [ ]:
arr.reshape(5,5)# precisa ter a mesma quantidade de elementos: 25 elementos podem virar 5x5, mas não 4x4.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**Aplicação direta no TCC**

Esse `reshape(5,5)` é pequeno, mas a ideia escala.

Se eu tiver 10.000 bytes, posso tentar transformar em uma matriz 100x100. Se tiver mais bytes, posso cortar, preencher ou redimensionar. Essas escolhas precisam ser documentadas porque afetam o resultado do modelo.

**Máximo, mínimo e posição dos valores**

Além de saber o maior ou menor valor, às vezes quero saber **onde** esse valor está.

Em análise de malware como imagem, isso pode ajudar a localizar regiões com valores altos, padrões concentrados, ou áreas específicas que chamam atenção no array.

In [35]:
print(ranarr.max())
print(ranarr.argmax()) # retorna o índice do maior valor
print(ranarr.min())
print(ranarr.argmin()) # retorna o índice do menor valor

40
6
0
5


**Shape**

`shape` mostra o formato do array.

Isso é fundamental porque modelos de machine learning e deep learning esperam entrada em formatos específicos. Se a dimensão estiver errada, o modelo geralmente quebra ou aprende errado.

In [41]:
print(arr.shape) # retorna o formato/dimensão do array
arr = arr.reshape(5,5)
print(arr.shape)

(25,)
(5, 5)


**Tipo dos dados**

`dtype` mostra o tipo dos valores dentro do array.

Isso importa muito. Bytes normalmente ficam entre 0 e 255. Imagens podem ser `uint8`, features podem ser `float32`, modelos podem esperar `float32`. Ignorar tipo de dado pode causar bug silencioso.

In [43]:
arr.dtype

dtype('int64')

**Import específico**

Também dá para importar uma função específica do NumPy. Aqui o exemplo importa `randint` direto.

Eu particularmente prefiro usar `np.random.randint()` na maioria dos casos, porque fica mais explícito de onde a função veio.

In [44]:
from numpy.random import randint

In [45]:
randint(0,100)

3

**Resumo desta primeira parte**

Até aqui, o essencial é:

- criar arrays;
- criar matrizes;
- gerar valores automaticamente;
- entender shape;
- entender tipo de dado;
- reorganizar dados com reshape.

Para minha pesquisa, isso é a base para representar binários, features e imagens.

## NumPy Array Indexing and Selection

Aqui começa uma parte muito importante: **acessar pedaços específicos do array**.

Isso parece básico, mas é o tipo de coisa que fica aparecendo toda hora em análise de dados. Em malware, por exemplo, posso querer pegar só um intervalo de bytes, só uma região de uma matriz, só as primeiras linhas de uma imagem, ou só os valores que passam em uma condição.

Essa parte é sobre pegar exatamente o pedaço que eu quero, sem precisar fazer gambiarra com loop manual o tempo inteiro.

In [1]:
import numpy as np

**Array simples para treinar indexação**

Agora o notebook cria um array de 0 até 10. Esse é o tipo de exemplo bom para aprender slicing sem se perder.

In [12]:
arrI = np.arange(0,11)

In [13]:
arrI

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Acessando por índice**

Assim como listas, arrays começam no índice 0.

Então `arrI[8]` pega o elemento que está na posição 8.

In [5]:
arrI[8]

np.int64(8)

**Slicing**

Slicing é pegar um pedaço do array.

A regra principal é: o início entra, o fim não entra. Então `[1:5]` pega os índices 1, 2, 3 e 4.

In [7]:
print(arrI[1:5]) # slicing: retorna os elementos do índice 1 até o 4
print(arrI[0:5]) # slicing: retorna os elementos do índice 0 até o 4
print(arrI[:6]) # slicing: retorna os elementos do índice 0 até o 5
print(arrI[5:]) # slicing: retorna os elementos do índice 5 até o final

[1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4 5]
[ 5  6  7  8  9 10]


**View: cuidado real aqui**

Essa parte é muito importante. Em NumPy, um slice pode ser uma **view**, ou seja, uma visão do array original.

Então se eu altero o slice, posso acabar alterando o array original também. Isso é perigoso se eu estiver mexendo em dados de treino ou features originais sem perceber.

In [14]:
print(arrI)

slice_of_arrI = arrI[0:5]
slice_of_arrI[:] = 100

print(slice_of_arrI)
print(arrI)#O slice_of_arrI é uma view do arrI, então quando alteramos o slice_of_arrI, o arrI também é alterado

[ 0  1  2  3  4  5  6  7  8  9 10]
[100 100 100 100 100]
[100 100 100 100 100   5   6   7   8   9  10]


**Copy**

Quando eu quero uma cópia independente, uso `.copy()`.

Essa diferença entre view e copy é importante para não contaminar dados sem querer.

In [15]:
arrI_copy = arrI.copy() #Diferente do slice, o copy cria uma cópia do array, então quando alteramos o copy, o arrI não é alterado

In [16]:
arrI_copy[:] = 200

In [17]:
print(arrI)
print(arrI_copy)

[100 100 100 100 100   5   6   7   8   9  10]
[200 200 200 200 200 200 200 200 200 200 200]


**Moral da história: view vs copy**

Essa parte parece detalhe, mas não é.

Se eu estiver preparando um dataset e alterar uma view achando que é cópia, posso modificar dados originais sem perceber. Isso pode gerar erro difícil de achar depois.

Regra prática: quando for mexer em um pedaço e eu não quiser alterar o original, uso `.copy()`.

**Arrays 2D**

Agora entramos em arrays bidimensionais. Isso é diretamente ligado à ideia de imagem.

Uma imagem em escala de cinza pode ser vista como uma matriz 2D: linha, coluna e valor do pixel.

In [18]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [19]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

**Indexação em matriz**

Aqui aparecem duas formas de acessar valores:

- `arr_2d[linha][coluna]`
- `arr_2d[linha, coluna]`

A segunda forma costuma ser mais comum em NumPy.

In [25]:
print(arr_2d[1][1]) #Retorna o elemento da segunda linha e segunda coluna, que é 25
print(arr_2d[0]) #Retorna a primeira linha do array, que é [5,10,15]
print(arr_2d[0:2]) #Retorna as duas primeiras linhas do array, que são [[5,10,15],[20,25,30]]
print(arr_2d[2][1]) #Retorna o elemento da terceira linha e segunda coluna, que é 40

# Outra notação para acessar elementos de arrays 2D é usando vírgula para separar os índices de linha e coluna:

print(arr_2d[1,1]) #Retorna o elemento da segunda linha e segunda coluna, que é 25
print(arr_2d[:2,1:]) #Retorna as duas primeiras linhas e todas as colunas a partir da segunda coluna, que são [[10,15],[25,30]]
print(arr_2d[1:,:2]) #Retorna todas as linhas a partir da segunda linha e as duas primeiras colunas, que são [[20,25],[35,40]]

25
[ 5 10 15]
[[ 5 10 15]
 [20 25 30]]
40
25
[[10 15]
 [25 30]]
[[20 25]
 [35 40]]


**Aplicação em imagem de malware**

Se eu transformar um binário em imagem, posso querer pegar regiões específicas:

- começo do arquivo;
- cabeçalho;
- seções específicas;
- blocos com maior entropia;
- pedaços que o modelo parece considerar importantes.

Toda essa lógica depende de saber indexar e fatiar matrizes.

**Máscaras booleanas**

Aqui começa uma parte muito útil: criar condições sobre arrays.

Isso permite selecionar apenas os valores que satisfazem uma regra, sem precisar fazer loop manual.

In [26]:
arr_1d = np.arange(1,11)

In [27]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
bool_arr_1d =  arr_1d > 5

In [31]:
bool_arr_1d

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [33]:
arr_1d[bool_arr_1d] #Retorna os elementos do arr_1d que são maiores que 5

array([ 6,  7,  8,  9, 10])

In [34]:
arr_1d[arr_1d > 3] #Retorna os elementos do arr_1d que são maiores que 3

array([ 4,  5,  6,  7,  8,  9, 10])

**Máscara booleana na pesquisa**

Isso aqui é muito útil para filtrar dados.

Exemplos possíveis:

- pegar apenas amostras com tamanho maior que X;
- pegar apenas pixels acima de certo valor;
- filtrar scores acima de um threshold;
- selecionar famílias com quantidade mínima de amostras;
- remover valores inválidos.

Esse tipo de filtro vai aparecer bastante quando eu estiver limpando dataset e analisando resultados.

#### Exercise:

Crie um novo array 2D com `np.arange(50)` e depois reorganize ele para o formato `5,10`.

Depois, pegue alguns pedaços desse array usando slicing.

Esse exercício é bom porque parece bobo, mas é exatamente a lógica que vou usar quando estiver cortando matrizes, imagens ou blocos de dados derivados de binários.

**Exercício de matriz 5x10**

Esse exercício treina exatamente a habilidade de transformar vetor em matriz e depois selecionar pedaços.

Na pesquisa, isso lembra bastante a lógica de transformar bytes em uma matriz que depois pode virar imagem.

In [36]:
arr_2D = np.arange(50).reshape(5,10)

In [37]:
arr_2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [38]:
print(arr_2D[1:3, 2:5]) #Retorna as linhas 1 e 2 e as colunas 2, 3 e 4 do array arr_2D
print(arr_2D[:2, 5:]) #Retorna as duas primeiras linhas e as colunas a partir da quinta coluna do array arr_2D

[[12 13 14]
 [22 23 24]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]


**Comentário sobre o exercício**

Esse exercício treina exatamente o que vou precisar quando estiver trabalhando com matrizes maiores.

No começo parece só indexação, mas depois isso vira manipulação de imagem, recorte de regiões e preparação de dados para modelo.

## NumPy Operations

Nesta parte entram operações matemáticas com arrays.

- Array com Array
- Array com Escalares
- Funções universais do NumPy

A moral aqui é: o NumPy aplica a operação em vários elementos de uma vez. Eu não preciso fazer um `for` para somar, multiplicar, elevar ao quadrado ou tirar raiz de cada elemento. Isso é muito útil quando estou lidando com milhares de features ou muitos bytes de uma amostra.

In [1]:
import numpy as np

**Operações entre arrays**

Quando faço `arr + arr`, o NumPy soma elemento com elemento.

Isso é bem diferente de lista comum do Python. Com NumPy, a operação é vetorizada.

In [2]:
arr = np.arange(0,11)

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

**Array com escalar**

Aqui cada elemento do array recebe a mesma operação.

Isso é muito usado para normalização. Por exemplo, bytes de 0 a 255 podem ser divididos por 255 para virar valores entre 0 e 1 antes de entrar em um modelo.

In [8]:
print(arr + 100)
print(arr * 2)
print(arr ** 2) #Eleva cada elemento do array ao quadrado

[100 101 102 103 104 105 106 107 108 109 110]
[ 0  2  4  6  8 10 12 14 16 18 20]
[  0   1   4   9  16  25  36  49  64  81 100]


**Normalização**

Essa parte é importante para machine learning.

Se os valores vêm de bytes, normalmente estão entre 0 e 255. Muitos modelos funcionam melhor quando os dados são normalizados, por exemplo entre 0 e 1.

Exemplo conceitual:

`bytes_normalizados = bytes_array / 255`

Isso não está no notebook original, mas é uma ideia muito importante para o projeto.

**Divisão por zero**

Aqui aparece um aviso importante: dividir zero por zero gera `nan`.

`nan` significa “not a number”. Em dataset real, esse tipo de valor pode ferrar treino, métrica e análise se eu não tratar direito.

In [10]:
arr / arr #retorna nan para o elemento 0, pois não é possível dividir por 0

C:\Users\gabri\AppData\Local\Temp\ipykernel_24484\55995797.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr #retorna nan para o elemento 0, pois não é possível dividir por 0


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

**Funções universais**

Funções como `sqrt`, `exp`, `log` e `sin` são aplicadas em todos os elementos do array.

Isso é útil para transformação matemática de features, embora eu precise sempre pensar se a transformação faz sentido para o problema.

In [11]:
np.sqrt(arr) #Retorna a raiz quadrada de cada elemento do array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [12]:
np.exp(arr) #Retorna o exponencial de cada elemento do array

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [13]:
np.log(arr) #Retorna o logaritmo natural de cada elemento do array

C:\Users\gabri\AppData\Local\Temp\ipykernel_24484\2859866470.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) #Retorna o logaritmo natural de cada elemento do array


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [14]:
np.sin(arr) #Retorna o seno de cada elemento do array

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

## Como isso conversa com minha pesquisa

NumPy entra na minha pesquisa em várias partes:

1. **Ler dados brutos**
   - binários podem virar sequências de bytes;
   - sequências de bytes podem virar arrays.

2. **Criar representação visual**
   - um array 1D pode virar matriz;
   - uma matriz pode virar imagem em escala de cinza.

3. **Preparar dataset**
   - normalizar valores;
   - verificar shapes;
   - filtrar amostras;
   - separar features e labels.

4. **Evitar bugs**
   - entender `dtype`;
   - evitar alteração acidental com views;
   - tratar `nan` e `inf`;
   - garantir que todas as entradas tenham formato compatível.

5. **Analisar resultados**
   - calcular médias;
   - comparar arrays;
   - aplicar máscaras;
   - investigar regiões de interesse.

A ideia principal é: NumPy não é só “matemática em Python”. Para o meu TCC, ele é uma ferramenta para transformar dados crus em uma forma que modelos de ML/DL conseguem usar.